name: CI
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn, build
        run: |
          yarn
          yarn build
        env:
          GITHUB_API_TOKEN: 54726d21cec52f451376fcbc28525527c28da672
      - name: run Lighthouse CI
        run: |
          sudo yarn global add @lhci/cli@0.4.x
          lhci autorun
